version: 2
registries:
  k9-rapid:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-rapid
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: "/app"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "no.nav.helse:dusseldorf*"
        versions: ["6.0.0"]
      - dependency-name: "io.ktor:ktor*"
        versions: [">=3.0.0"] #krever at dusseldorf migreres til 3.0.0 først
    groups:
      nav-deps:
        patterns:
          - "*no.nav*"
        exclude-patterns:
          - "*ktor*"
          - "*dusseldorf*"
      ktor-deps:
        patterns:
          - "*ktor*"
          - "*dusseldorf*"
      annet-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "*ktor*"
          - "*dusseldorf*"
          - "*no.nav*"
    registries:
      - k9-rapid

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
