openapi: 3.0.1
info:
  title: Omsorgsdager
  description: Håndtering av omsorgsdager
  contact:
    email: omsorgspenger@nav.no
  license:
    name: MIT
    url: https://github.com/navikt/omsorgsdager/blob/main/LICENSE
  version: 1.0.0
servers:
- url: https://omsorgsdager.dev.intern.nav.no/api
- url: https://omsorgsdager.intern.nav.no/api
tags:
- name: Utvidet rett - skriv
  description: Skriveoperasjoner for utvidet rett
- name: Utvidet rett - les
  description: Leseoperasjoner for utvidet rett
paths:
  /utvidet-rett:
    post:
      tags:
      - Utvidet rett - skriv
      summary: Registrere ny søknad om utvidet rett
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UtvidetRettSoknad'
        required: true
      responses:
        201:
          description: Opprettet et vedtak. Ved opprettelse vil det alltid ha status=FORSLAG
            ettersom det minst vil være ett aksjonspunkt som kreves.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetRettSoknadResponse'
  /utvidet-rett/{behandlingId}/aksjonspunkt:
    put:
      tags:
      - Utvidet rett - skriv
      parameters:
      - name: behandlingId
        in: path
        description: Behandling ID
        required: true
        schema:
          type: string
      summary: Legge til eller oppdatere aksjonspunkt
      requestBody:
        description: Legge til/oppdatere løsning på aksjonspunkt. Kan sende med på ett eller flere aksjonspunkt samtidig.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AksjonspunktRequest'
        required: true
      responses:
        200:
          description: Oppdatert vedtak etter at aksjonspunkt er løst, som gjenspeiles i 'kreverAksjonspunter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetRettSoknadResponse'
  /utvidet-rett/{behandlingId}/fastsett:
    put:
      tags:
      - Utvidet rett - skriv
      summary: Fastsette vedtaket
      parameters:
      - name: behandlingId
        in: path
        description: Behandling ID
        required: true
        schema:
          type: string
      responses:
        200:
          description: Status=FASTSATT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetRettSoknadResponse'
        409:
          description: Om det er uløste aksjonspunkter på vedtaket. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetRettSoknadResponse'
  /utvidet-rett/{behandlingId}/deaktiver:
    put:
      tags:
      - Utvidet rett - skriv
      summary: Deaktiver vedtaket
      parameters:
      - name: behandlingId
        in: path
        description: Behandling ID
        required: true
        schema:
          type: string
      responses:
        200:
          description: Status=DEAKTIVERT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtvidetRettSoknadResponse'
  /utvidet-rett/{behandlingId}:
    get:
      tags:
      - Utvidet rett - les
      parameters:
      - name: behandlingId
        in: path
        description: Behandling ID
        required: true
        schema:
          type: string
      summary: Hente et vedtak
      responses:
        200:
          description: Henter vedtaket slik det ser ut nå
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentUtvidetRettResponse'
  /utvidet-rett/{p}:
    get:
      tags:
      - Utvidet rett - les
      parameters:
      - name: saksnummer
        in: path
        required: true
        schema:
          type: string
          example: ABC123
      - name: status
        in: query
        description: Status
        required: false
        schema:
          type: string
          description: Filtrering på status
          enum:
          - FORSLAG
          - FASTSATT
          - DEAKTIVERT
      - name: gyldigFraOgMed
        in: query
        required: false
        schema:
          type: string
          format: date
          example: "2020-01-01"
      - name: gyldigTilOgMed
        in: query
        required: false
        schema:
          type: string
          format: date
          example: "2020-02-01"
      summary: Hente alle vedtak på saksnummer med filtrering
      responses:
        200:
          description: Henter alle vedtak for et saksnummer med filtrering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentAlleUtvidetRettResponse'
components:
  schemas:
    UtvidetRettSoknad:
      type: object
      properties:
        saksnummer:
          type: string
          format: string
          example: '"OBC123"'
        behandlingId:
          type: string
          format: string
          example: '"UUID-123-123"'
        mottatt:
          type: string
          format: date-time
        søker:
          $ref: '#/components/schemas/Soker'
        barn:
          $ref: '#/components/schemas/Barn'
    Soker:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '"29099011112"'
        fødselsdato:
          type: string
          format: date
        jobberINorge:
          type: boolean
    Barn:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '"29099011111"'
        fødselsdato:
          type: string
          format: date
    UtvidetRettSoknadResponse:
      type: object
      properties:
        status:
          type: string
          description: Status på vedtaket
          enum:
          - FORSLAG
          - FASTSATT
          - DEAKTIVERT
        uløsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties: {}
            MEDLEMSKAP:
              type: object
              properties: {}
            YRKESAKTIVITET:
              type: object
              properties: {}
    AksjonspunktRequest:
      type: object
      properties:
        LEGEERKLÆRING:
          type: object
          properties: {}
        MEDLEMSKAP:
          type: object
          properties: {}
        YRKESAKTIVITET:
          type: object
          properties: {}
    HentUtvidetRettResponse:
      type: object
      properties:
        barn:
          $ref: '#/components/schemas/Barn'
        gyldigFraOgMed:
          type: string
          format: date
        gyldigTilOgMed:
          type: string
          format: date
        status:
          type: string
          description: Status på vedtaket
          enum:
          - FORSLAG
          - FASTSATT
          - DEAKTIVERT
        uløsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties: {}
        løsteAksjonspunkter:
          type: object
          properties:
            MEDLEMSKAP:
              type: object
              properties: {}
            YRKESAKTIVITET:
              type: object
              properties: {}
        lovhenvisnigner:
          type: object
          properties:
            FTL 9-5 3.ledd:
              type: string
              example: "søkeren bor ikke i norge"
            FTL 9-5 2.ledd:
              type: string
              example: "ikke omsorgen for barnet"
    HentAlleUtvidetRettResponse:
      type: object
      properties:
        vedtak:
          type: array
          items:
            $ref: '#/components/schemas/HentUtvidetRettResponse'
      