openapi: 3.0.1
info:
  title: Omsorgsdager
  description: >
    Håndtering av omsorgsdager<br/><br/>
    <b>Utvidet rett omfatter</b><br>
    - Kronisk sykt barn<br/>
    - Midliertidig alene</br></br>

    <b>Autentisering & autorisering</b></br>
    <b>Generelt</b></br>
    - Authorization header med `Bearer` scheme</br>
    - `les`-operasjoner med persontoken kan gjøres for alle i en `k9-*`-gruppe</br>
    - `skriv`-operasjoner med persontoken kan gjøres kun av `saksbehandler/overstyrer/beslutter`</br>
    - Ha lov til å se detaljer om de involverte partene i behandlingen (mtp. skjermingskoder/egen ansatt)</br>
    - `HTTP 401` ved manglende/ikke støttet token</br>
    - `HTTP 403` ved manglende tilganger</br>
    - Ved kjøring lokalt gå på `http://localhost:8082/access-tokens` for å få access tokens som kan brukes i Swagger.</br>
    <b>Azure</b></br>
    - System & persontoken scopet til omsorgsdager-tjenesten (`audience`)</br>
    - Systemtokens må ha `role=access_as_application`</br>
    <b>OpenAM</b></br>
    - Systemtokens må tilhøre en client som er allowlisted i tjenesten (`azp`)
  contact:
    email: omsorgspenger@nav.no
  license:
    name: MIT
    url: https://github.com/navikt/omsorgsdager/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://omsorgsdager.dev.intern.nav.no/api
  - url: https://omsorgsdager.intern.nav.no/api
  - url: http://localhost:8081/api
tags:
  - name: Kronisk sykt barn - skriv
    description: Skriveoperasjoner for kronisk sykt barn
  - name: Kronisk sykt barn - les
    description: Leseoperasjoner for kronisk sykt barn
paths:
  /kronisk-sykt-barn:
    post:
      tags:
        - Kronisk sykt barn - skriv
      summary: Registrere ny vedtak for kronisk sykt barn
      description: >
        - `identitetsnummer` på barn er optional.</br>

        - Om det allerede finnes et vedtak på samme `behandlingId` som fortsatt har status `FORESLÅTT`
        vil det nye grunlaget erstatte det som lå der. Om den eksisterende har en annen status enn `FORESLÅTT`
        vil det feile med HTTP 409.</br>

        - `tidspunkt` er optional, defaulter til utc now
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpprettKroniskSyktBarnRequest'
        required: true
      security:
        - accessToken: []
      responses:
        201:
          description: >
            - Opprettet et vedtak. Ved opprettelse vil det alltid ha `status=FORESLÅTT`
            ettersom det minst vil være ett behov i `uløsteBehov`

            - `potensielleStatuser` inneholder liste om potensielle statuser vedtaket kan havne i.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpprettKroniskSyktBarnResponse'
        409:
          description: Om det allerede er sendt inn et vedtak med samme behandlingId som har status != `FORESLÅTT`
    get:
      tags:
        - Kronisk sykt barn - les
      description: >
        - Henter vedtak om kronisk sykt barn<br/>
        Enten for en behandling id eller aggregert for et saksnummer.</br>

        - For `saksnummer+barn+periode` man kun ha ett vedtak, så vil kun være det siste som blir aggregert på saksnummer med status enten `INNVILGET` eller `AVSLÅTT`</br>

        - Må sette enten saksnummer eller behandlingId. Ikke begge.<br/>

        - `gyldigFraOgMed` & `gyldigTilogMed` er optional.
      parameters:
        - name: saksnummer
          in: query
          required: false
          schema:
            type: string
            example: ABC123
        - name: behandlingId
          in: query
          required: false
          schema:
            type: string
            example: UUID-123
        - name: gyldigFraOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-01-01"
        - name: gyldigTilOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-02-01"
      summary: Hente vedtak
      security:
        - accessToken: []
      responses:
        200:
          description: Henter alle vedtak for et saksnummer med filtrering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentGjeldendeKroniskSyktBarnResponse'
  /kronisk-sykt-barn/{behandlingId}/løst:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      summary: Legge til eller oppdatere behov
      requestBody:
        description: >
          - Legge til/oppdatere løsning på behov. Kan sende med på ett eller flere behov samtidig.<br/>

          - For de behovene som inneholder informasjon overskrives eventuell tidligere vurderinger gjort på behovet.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LostBehovRequest'
        required: true
      security:
        - accessToken: []
      responses:
        200:
          description: >
            - Oppdatert vedtak etter at behov er løst, som gjenspeiles at det/de som ble løst nå er borte fra `uløsteBehov`</br>

            - Om `potensielleStatuser` ikke inneholder `INNVILGET` betyr det at vedtaket ikke kan innvilges ettersom en av løsningene på aksjonspuntene indikerer at det må bli `AVSLÅTT` eller `FORKASTET`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpprettKroniskSyktBarnResponse'
        409:
          description: >
            - Om vedtaket har en annen status enn `FORESLÅTT`<br/>

  /kronisk-sykt-barn/{behandlingId}/innvilget:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Innvilge vedtaket
      description: >
        - `tidspunkt` er optional, defaulter til utc now
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndreVedtakStatusRequest'
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      security:
        - accessToken: []
      responses:
        200:
          description: >
            `status=INNVILGET`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpprettKroniskSyktBarnResponse'
        409:
          description: >
            - Om det er uløste behov<br/>

            - Om vedtaket før innvilgelse har en annen status enn `FORESLÅTT`<br/>

            - Om løsningene på et eller fler behov indikerer at vedtaket ikke kan innvilges
  /kronisk-sykt-barn/{behandlingId}/avslått:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Avslå vedtaket
      description: >
        - `tidspunkt` er optional, defaulter til utc now
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndreVedtakStatusRequest'
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      security:
        - accessToken: []
      responses:
        200:
          description: >
            `status=AVSLÅTT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpprettKroniskSyktBarnResponse'
        409:
          description: >
            - Om vedtaket før avslag har en annen status enn `FORESLÅTT`
  /kronisk-sykt-barn/{behandlingId}/forkastet:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Forkaste vedtaket
      description: >
        - `tidspunkt` er optional, defaulter til utc now
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndreVedtakStatusRequest'
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      security:
        - accessToken: []
      responses:
        200:
          description: >
            `status=FORKASTET`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpprettKroniskSyktBarnResponse'
        409:
          description: >
            - Om vedtaket før forkasting har en annen status enn `FORESLÅTT`
components:
  schemas:
    OpprettKroniskSyktBarnRequest:
      type: object
      properties:
        saksnummer:
          type: string
          format: string
          example: 'OBC123'
        behandlingId:
          type: string
          format: string
          example: 'UUID-123-123'
        tidspunkt:
          type: string
          format: date-time
        søknadMottatt:
          type: string
          format: date-time
        søker:
          $ref: '#/components/schemas/Soker'
        barn:
          $ref: '#/components/schemas/Barn'
    Soker:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '29099011112'
    Barn:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '29099011111'
        fødselsdato:
          type: string
          format: date
        harSammeBosted:
          type: boolean
          example: true
    OpprettKroniskSyktBarnResponse:
      type: object
      properties:
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORESLÅTT
            - INNVILGET
            - AVSLÅTT
            - FORKASTET
        potensielleStatuser:
          type: object
          properties:
            INNVILGET:
              type: object
              properties: {}
            AVSLÅTT:
              type: object
              properties: {}
            FORKASTET:
              type: object
              properties: {}
        uløsteBehov:
          type: object
          properties:
            VURDERE_KRONISK_SYKT_BARN:
              type: object
              properties: {}
            VURDERE_OMSORGEN_FOR:
              type: object
              properties: {}
    LostBehovRequest:
      type: object
      properties:
        VURDERE_KRONISK_SYKT_BARN:
          type: object
          properties:
            vurdering:
              type: string
              example: Dette er saksbehandlers vurdering
            barnetErKroniskSyktEllerHarEnFunksjonshemning:
              type: boolean
              example: true
            erSammenhengMedSøkersRisikoForFraværFraArbeid:
              type: boolean
              example: true
        VURDERE_OMSORGEN_FOR:
          type: object
          properties: {}
    Lovhenvisninger:
      type: object
      properties:
        innvilget:
          type: object
          properties:
            "Ftrl. § 9-6 andre ledd":
              type: array
              items:
                type: string
                example: "Barnet er kronisk sykt eller har en funksjonshemning."
            "Ftrl. § 9-5 fjerde ledd andre punktum":
              type: array
              items:
                type: string
                example: "Perioden gjelder fra dagen søknaden ble mottatt ut året barnet fyller 18 år."
        avslått:
          type: object
          properties:
            "Ftrl. § 9-6 andre ledd":
              type: array
              items:
                type: string
                example: "Er ikke sammenheng med søkers risiko for fravær fra arbeidet."
    VurdereKroniskSyktBarnLostBehov:
      type: object
      properties:
        grunnlag:
          type: object
        lovhenvisninger:
          $ref: '#/components/schemas/Lovhenvisninger'
        løsning:
          type: object
          properties:
            vurdering:
              type: string
              example: Dette er saksbehandlers vurdering
            barnetErKroniskSyktEllerHarEnFunksjonshemning:
              type: boolean
              example: true
            erSammenhengMedSøkersRisikoForFraværFraArbeid:
              type: boolean
              example: true
    HentKroniskSyktBarnResponse:
      type: object
      properties:
        behandlingId:
          type: string
          format: string
          example: UUID-123-123
        gyldigFraOgMed:
          type: string
          format: date
        gyldigTilOgMed:
          type: string
          format: date
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORESLÅTT
            - INNVILGET
            - AVSLÅTT
            - FORKASTET
        grunnlag:
          $ref: '#/components/schemas/OpprettKroniskSyktBarnRequest'
        uløsteBehov:
          type: object
          properties:
            VURDERE_OMSORGEN_FOR:
              type: object
              properties: {}
        løsteBehov:
          type: object
          properties:
            VURDERE_KRONISK_SYKT_BARN:
              $ref: '#/components/schemas/VurdereKroniskSyktBarnLostBehov'
    HentGjeldendeKroniskSyktBarnResponse:
      type: object
      properties:
        vedtak:
          type: array
          items:
            $ref: '#/components/schemas/HentKroniskSyktBarnResponse'
    EndreVedtakStatusRequest:
      type: object
      properties:
        tidspunkt:
          type: string
          format: date-time
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
