openapi: 3.0.1
info:
  title: Omsorgsdager
  description: >
    Håndtering av omsorgsdager<br/><br/>
    <b>Utvidet rett omfatter</b><br>
    - Kronisk sykt barn<br/>
    - Midliertidig alene</br></br>

    <b>Autentisering & autorisering</b></br>
    <b>Generelt</b></br>
    - Authorization header med `Bearer` scheme</br>
    - `les`-operasjoner med persontoken kan gjøres for alle i en `k9-*`-gruppe</br>
    - `skriv`-operasjoner med persontoken kan gjøres kun av `saksbehandler/overstyrer/beslutter`</br>
    - Ha lov til å se detaljer om de involverte partene i behandlingen (mtp. skjermingskoder/egen ansatt)</br>
    - `HTTP 401` ved manglende/ikke støttet token</br>
    - `HTTP 403` ved manglende tilganger</br>
    <b>Azure</b></br>
    - System & persontoken scopet til omsorgsdager-tjenesten (`audience`)</br>
    - Systemtokens må ha `role=access_as_application`</br>
    <b>OpenAM</b></br>
    - Systemtokens må tilhøre en client som er allowlisted i tjenesten (`azp`)
  contact:
    email: omsorgspenger@nav.no
  license:
    name: MIT
    url: https://github.com/navikt/omsorgsdager/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://omsorgsdager.dev.intern.nav.no/api
  - url: https://omsorgsdager.intern.nav.no/api
tags:
  - name: Kronisk sykt barn - skriv
    description: Skriveoperasjoner for kronisk sykt barn
  - name: Kronisk sykt barn - les
    description: Leseoperasjoner for kronisk sykt barn
paths:
  /kronisk-sykt-barn:
    post:
      tags:
        - Kronisk sykt barn - skriv
      summary: Registrere ny søknad for kronisk sykt barn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KroniskSyktBarnSoknadRequest'
        required: true
      responses:
        201:
          description: >
            - Opprettet et vedtak. Ved opprettelse vil det alltid ha `status=FORSLAG`
            ettersom det minst vil være ett aksjonspunkt i `uløsteAksjonspunkter`

            - `potensielleStatuser` inneholder liste om potensielle statuser vedtaket kan havne i.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: Om det allerede er sendt inn et vedtak med samme behandlingId
    get:
      tags:
        - Kronisk sykt barn - les
      description: >
        - Henter vedtak om kronisk sykt barn<br/>
        Enten for en behandling id eller aggregert for et saksnummer.</br>

        - For `saksnummer+barn+periode` man kun ha ett vedtak, så vil kun være det siste som blir aggregert på saksnummer med status enten `INNVILGET` eller `AVSLÅTT`</br>

        - Må sette enten saksnummer eller behandlingId. Ikke begge.<br/>

        - `gyldigFraOgMed` & `gyldigTilogMed` er optional.
      parameters:
        - name: saksnummer
          in: query
          required: false
          schema:
            type: string
            example: ABC123
        - name: behandlingId
          in: query
          required: false
          schema:
            type: string
            example: UUID-123
        - name: gyldigFraOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-01-01"
        - name: gyldigTilOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-02-01"
      summary: Hente vedtak
      responses:
        200:
          description: Henter alle vedtak for et saksnummer med filtrering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentGjeldendeKroniskSyktBarnResponse'
  /kronisk-sykt-barn/{behandlingId}/aksjonspunkt:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      summary: Legge til eller oppdatere aksjonspunkt
      requestBody:
        description: >
          - Legge til/oppdatere løsning på aksjonspunkt. Kan sende med på ett eller flere aksjonspunkt samtidig.<br/>

          - For de aksjonspunktene som inneholder informasjon overskrives eventuell tidligere vurderinger gjort på aksjonspunktet.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AksjonspunktRequest'
        required: true
      responses:
        200:
          description: >
            - Oppdatert vedtak etter at aksjonspunkt er løst, som gjenspeiles at det/de som ble løst nå er borte fra `uløsteAksjonspunkter`</br>

            - Om `potensielleStatuser` ikke inneholder `INNVILGET` betyr det at vedtaket ikke kan innvilges ettersom en av løsningene på aksjonspuntene indikerer at det må bli `AVASLÅTT` eller `DEAKTIVERT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: >
            - Om vedtaket har en annen status enn `FORSLAG`<br/>

  /kronisk-sykt-barn/{behandlingId}/innvilgelse:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Innvilge vedtaket
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: >
            `status=INNVILGET`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: >
            - Om det er uløste aksjonspunkt<br/>

            - Om vedtaket før innvilgelse har en annen status enn `FORSLAG`<br/>

            - Om løsningene på et eller fler aksjonspunkt indikerer at vedtaket ikke kan innvilges
  /kronisk-sykt-barn/{behandlingId}/avslag:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Avslå vedtaket
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: >
            `status=AVSLÅTT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: >
            - Om vedtaket før avslag har en annen status enn `FORSLAG`
  /kronisk-sykt-barn/{behandlingId}/deaktivering:
    patch:
      tags:
        - Kronisk sykt barn - skriv
      summary: Deaktivere vedtaket
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: >
            `status=DEAKTIVERT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: >
            - Om vedtaket før deaktivering har en annen status enn `FORSLAG`
components:
  schemas:
    KroniskSyktBarnSoknadRequest:
      type: object
      properties:
        saksnummer:
          type: string
          format: string
          example: 'OBC123'
        behandlingId:
          type: string
          format: string
          example: 'UUID-123-123'
        mottatt:
          type: string
          format: date-time
        søker:
          $ref: '#/components/schemas/Soker'
        barn:
          $ref: '#/components/schemas/Barn'
    Soker:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '29099011112'
        fødselsdato:
          type: string
          format: date
    Barn:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '29099011111'
        fødselsdato:
          type: string
          format: date
        harSammeBosted:
          type: boolean
          example: true
    KroniskSyktBarnSoknadResponse:
      type: object
      properties:
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORSLAG
            - INNVILGET
            - AVSLÅTT
            - DEAKTIVERT
        potensielleStatuser:
          type: array
          items:
            type: string
            example: 'DEAKTIVERT'
        uløsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties: {}
            OMSORGEN_FOR:
              type: object
              properties: {}
    AksjonspunktRequest:
      type: object
      properties:
        LEGEERKLÆRING:
          type: object
          properties:
            vurdering:
              type: string
              example: Dette er saksbehandlers vurdering
            barnetErKroniskSyktEllerHarEnFunksjonshemning:
              type: boolean
              example: true
            erSammenhengMedSøkersRisikoForFraværeFraArbeid:
              type: boolean
              example: true
        OMSORGEN_FOR:
          type: object
          properties: {}
    HentKroniskSyktBarnResponse:
      type: object
      properties:
        barn:
          $ref: '#/components/schemas/Barn'
        behandlingId:
          type: string
          format: string
          example: UUID-123-123
        gyldigFraOgMed:
          type: string
          format: date
        gyldigTilOgMed:
          type: string
          format: date
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORSLAG
            - INNVILGET
            - AVSLÅTT
            - DEAKTIVERT
        uløsteAksjonspunkter:
          type: object
          properties:
            OMSORGEN_FOR:
              type: object
              properties: {}
        løsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties:
                vurdering:
                  type: string
                  example: Dette er saksbehandlers vurdering
                barnetErKroniskSyktEllerHarEnFunksjonshemning:
                  type: boolean
                  example: true
                erSammenhengMedSøkersRisikoForFraværeFraArbeid:
                  type: boolean
                  example: true
        lovhenvisnigner:
          type: object
          properties:
            FTL 9-5 3.ledd:
              type: string
              example: "søkeren bor ikke i norge"
            FTL 9-5 2.ledd:
              type: string
              example: "ikke omsorgen for barnet"
    HentGjeldendeKroniskSyktBarnResponse:
      type: object
      properties:
        vedtak:
          type: array
          items:
            $ref: '#/components/schemas/HentKroniskSyktBarnResponse'
      