openapi: 3.0.1
info:
  title: Omsorgsdager
  description: >
    Håndtering av omsorgsdager<br/><br/>
    <b>Utvidet rett omfatter</b><br>
    - Kronisk sykt barn<br/>
    - Midliertidig alene</br></br>

    <b>Autentisering & autorisering</b></br>
    <b>Generelt</b></br>
    - Authorization header med `Bearer` scheme</br>
    - `les`-operasjoner med persontoken kan gjøres for alle i en `k9-*`-gruppe</br>
    - `skriv`-operasjoner med persontoken kan gjøres kun av `saksbehandler/overstyrer/beslutter`</br>
    - Ha lov til å se detaljer om de involverte partene i behandlingen (mtp. skjermingskoder/egen ansatt)</br>
    - `HTTP 401` ved manglende/ikke støttet token</br>
    - `HTTP 403` ved manglende tilganger</br>
    <b>Azure</b></br>
    - System & persontoken scopet til omsorgsdager-tjenesten (`audience`)</br>
    - Systemtokens må ha `role=access_as_application`</br>
    <b>OpenAM</b></br>
    - Systemtokens må tilhøre en client som er allowlisted i tjenesten (`azp`)
  contact:
    email: omsorgspenger@nav.no
  license:
    name: MIT
    url: https://github.com/navikt/omsorgsdager/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: https://omsorgsdager.dev.intern.nav.no/api
  - url: https://omsorgsdager.intern.nav.no/api
tags:
  - name: Kronisk sykt barn - skriv
    description: Skriveoperasjoner for kronisk sykt barn
  - name: Kronisk sykt barn - les
    description: Leseoperasjoner for kronisk sykt barn
paths:
  /kronisk-sykt-barn:
    post:
      tags:
        - Kronisk sykt barn - skriv
      summary: Registrere ny søknad for kronisk sykt barn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KroniskSyktBarnSoknadRequest'
        required: true
      responses:
        201:
          description: >
            - Opprettet et vedtak. Ved opprettelse vil det alltid ha `status=FORSLAG`
            ettersom det minst vil være ett aksjonspunkt i `uløsteAksjonspunkter`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
  /kronisk-sykt-barn/{behandlingId}/aksjonspunkt:
    put:
      tags:
        - Kronisk sykt barn - skriv
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      summary: Legge til eller oppdatere aksjonspunkt
      requestBody:
        description: >
          - Legge til/oppdatere løsning på aksjonspunkt. Kan sende med på ett eller flere aksjonspunkt samtidig.<br/>

          - For de aksjonspunktene som inneholder informasjon overskrives eventuell tidligere vurderinger gjort på aksjonspunktet.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AksjonspunktRequest'
        required: true
      responses:
        200:
          description: Oppdatert vedtak etter at aksjonspunkt er løst, som gjenspeiles i `uløsteAksjonspunkter`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: Om vedtaket allerede har `status=FASTSATT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
  /kronisk-sykt-barn/{behandlingId}/fastsett:
    put:
      tags:
        - Kronisk sykt barn - skriv
      summary: Fastsette vedtaket
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: >
            `status=FASTSATT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
        409:
          description: Om det er uløste aksjonspunkter på vedtaket.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
  /kronisk-sykt-barn/{behandlingId}/deaktiver:
    put:
      tags:
        - Kronisk sykt barn - skriv
      summary: Deaktiver vedtaket
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: >
            `status=DEAKTIVERT`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KroniskSyktBarnSoknadResponse'
  /kronisk-sykt-barn/{behandlingId}:
    get:
      tags:
        - Kronisk sykt barn - les
      parameters:
        - name: behandlingId
          in: path
          description: Behandling ID
          required: true
          schema:
            type: string
      summary: Hente et vedtak
      responses:
        200:
          description: Henter vedtaket slik det ser ut nå
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentKroniskSyktBarnResponse'
  /kronisk-sykt-barn/{saksnummer}:
    get:
      tags:
        - Kronisk sykt barn - les
      description: >
        - Henter vedtak om kronisk sykt barn aggregert for et saksnummer.</br>

        - For `saksnummer+barn+periode` man kun ha ett vedtak, så vil kun være det siste med `status=FASTSATT` som blir aggregert på saksnummer.
      parameters:
        - name: saksnummer
          in: path
          required: true
          schema:
            type: string
            example: ABC123
        - name: status
          in: query
          description: Status
          required: false
          schema:
            type: string
            description: Filtrering på status
            enum:
              - FORSLAG
              - FASTSATT
              - DEAKTIVERT
        - name: gyldigFraOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-01-01"
        - name: gyldigTilOgMed
          in: query
          required: false
          schema:
            type: string
            format: date
            example: "2020-02-01"
      summary: Hente alle vedtak på saksnummer med filtrering
      responses:
        200:
          description: Henter alle vedtak for et saksnummer med filtrering
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentGjeldendeKroniskSyktBarnResponse'
components:
  schemas:
    KroniskSyktBarnSoknadRequest:
      type: object
      properties:
        saksnummer:
          type: string
          format: string
          example: '"OBC123"'
        behandlingId:
          type: string
          format: string
          example: '"UUID-123-123"'
        mottatt:
          type: string
          format: date-time
        søker:
          $ref: '#/components/schemas/Soker'
        barn:
          $ref: '#/components/schemas/Barn'
    Soker:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '"29099011112"'
        fødselsdato:
          type: string
          format: date
        jobberINorge:
          type: boolean
    Barn:
      type: object
      properties:
        identitetsnummer:
          type: string
          format: string
          example: '"29099011111"'
        fødselsdato:
          type: string
          format: date
    KroniskSyktBarnSoknadResponse:
      type: object
      properties:
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORSLAG
            - FASTSATT
            - DEAKTIVERT
        uløsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties: {}
            MEDLEMSKAP:
              type: object
              properties: {}
            YRKESAKTIVITET:
              type: object
              properties: {}
    AksjonspunktRequest:
      type: object
      properties:
        LEGEERKLÆRING:
          type: object
          properties: {}
        MEDLEMSKAP:
          type: object
          properties: {}
        YRKESAKTIVITET:
          type: object
          properties: {}
    HentKroniskSyktBarnResponse:
      type: object
      properties:
        barn:
          $ref: '#/components/schemas/Barn'
        behandlingId:
          type: string
          format: string
          example: UUID-123-123
        gyldigFraOgMed:
          type: string
          format: date
        gyldigTilOgMed:
          type: string
          format: date
        status:
          type: string
          description: Status på vedtaket
          enum:
            - FORSLAG
            - FASTSATT
            - DEAKTIVERT
        uløsteAksjonspunkter:
          type: object
          properties:
            LEGEERKLÆRING:
              type: object
              properties: {}
        løsteAksjonspunkter:
          type: object
          properties:
            MEDLEMSKAP:
              type: object
              properties: {}
            YRKESAKTIVITET:
              type: object
              properties: {}
        lovhenvisnigner:
          type: object
          properties:
            FTL 9-5 3.ledd:
              type: string
              example: "søkeren bor ikke i norge"
            FTL 9-5 2.ledd:
              type: string
              example: "ikke omsorgen for barnet"
    HentGjeldendeKroniskSyktBarnResponse:
      type: object
      properties:
        vedtak:
          type: array
          items:
            $ref: '#/components/schemas/HentKroniskSyktBarnResponse'
      