name: Bygg mock
on:
  push:
    branches:
      - main
    paths:
      - 'mock/**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # ratchet:actions/checkout@v4
      - uses: nais/docker-build-push@3e3dd59e778ead7ba199dbfcde40350a178a2226 # ratchet:nais/docker-build-push@v0
        with:
          team: omsorgspenger
          push_image: true
          tag: latest
          image_suffix: mock
          pull: true
          dockerfile: mock/Dockerfile
          docker_context: mock/
          salsa: false # mock image, not deployed to NAIS
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
