name: Bygg mock
on:
  push:
    branches:
      - main
    paths:
      - 'mock/**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4
      - uses: nais/docker-build-push@5246e4705d79945a0ec28eb9bd3638dd534fee46 # ratchet:nais/docker-build-push@v0
        with:
          team: omsorgspenger
          push_image: true
          tag: latest
          image_suffix: mock
          pull: true
          dockerfile: mock/Dockerfile
          docker_context: mock/
          salsa: false # mock image, not deployed to NAIS
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
