name: Bygg mock
on:
  push:
    branches:
      - main
    paths:
      - 'mock/**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
      - uses: nais/docker-build-push@14cd7a0a656477da33aa7d627123330990ef3807 # ratchet:nais/docker-build-push@v0
        with:
          team: omsorgspenger
          push_image: true
          tag: latest
          image_suffix: mock
          pull: true
          dockerfile: mock/Dockerfile
          docker_context: mock/
          salsa: false # mock image, not deployed to NAIS
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
