name: Bygg mock

on:
  push:
    branches:
      - main
    paths:
      - 'mock/**'
env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}-mock
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Sette Docker Tag
        run: |
          echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Bygg & last opp Docker image
        run: |
          cd mock
          docker build --pull --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${BASE_IMAGE}:${TAG}
          docker push ${BASE_IMAGE}:latest
