name: Bygg mock
on:
  push:
    branches:
      - main
    paths:
      - 'mock/**'

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
      - uses: nais/docker-build-push@ea11cfb8d47d78fab1231145e34699714efad5b7 # ratchet:nais/docker-build-push@v0
        with:
          team: omsorgspenger
          push_image: true
          tag: latest
          image_suffix: mock
          pull: true
          dockerfile: mock/Dockerfile
          docker_context: mock/
          salsa: false # mock image, not deployed to NAIS
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
