name: Check and pin versions in workflows
on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
jobs:
  ratchet:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        asset: [
          build-mock.yaml,
          build-pull-request.yaml,
          test-build-deploy.yaml
        ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Check if ${{matrix.asset}} is pinned
        uses: 'docker://ghcr.io/sethvargo/ratchet@sha256:e5b2409be0d1c82c71a6e60c49027e539f4c90636529e4f8b5c25a68b68a36d4'
        with:
          args: 'check .github/workflows/${{matrix.asset}}'
          entrypoint: /ratchet
      - name: Checks failed
        if: ${{ failure() }}
        uses: 'docker://ghcr.io/sethvargo/ratchet@sha256:e5b2409be0d1c82c71a6e60c49027e539f4c90636529e4f8b5c25a68b68a36d4'
        with:
          args: 'pin .github/workflows/${{matrix.asset}}'
          entrypoint: /ratchet
      - name: Commit & Push changes
        if: ${{ failure() }}
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GITHUB_HEAD_REF }}
